### ISSUE TITLE
all contributor bot not working

### ISSUE THREAD

**Issue by balavishnuvj** [balavishnuvj/rtl-simple-queries#2]
What you did:
trying to add a contributor

What happened:
not getting contributor bot suggestion when I do `@` in PRs or Issues.

**Comment by kentcdodds** [comment]
@all-contributors please add @kentcdodds for ideas

**Comment by kentcdodds** [comment]
Huh. Why don't you try now @balavishnuvj

**Comment by balavishnuvj** [comment]
it works. ref: pr
#3
